### PR TITLE
Implementation of 24h clock, other language and unit

### PR DESCRIPTION
**Pull request by smileyn64**
Good evening,
I implemented:
- 24h clock
- other language and unit pulled from weather forecast
- locale module thread proof for international date conversion

### CODE REVIEW

**Comment by atainter** [comment]
Are all of your dependencies included with python 2.7?

**Comment by smileyn64** [comment]
I double checked and yes they are.
Also made some test by launching with Python 2.7, seems working like a charm.

**Comment by smileyn64** [comment]
for info, I let the variables independent for maximizing the personalization of the program.
e.g. I'm french, living in Indonesia, so like to have the UI in french but clock in 12h format, the US news and the weather of indonesia.

by the way I just added the AM/PM to the clock when the format is 12h.

**Comment by atainter** [comment]
LG. Nice work

**Pull request merged**
